'''Write a Menu driven program for following
 Area of circle (pi*r²)
 Area of Rectangle (l*b)
 Area of triangle (b*h/2)
 Area of Square (a²)'''
print("Enter Radius: ")
r=float(input())
a=(3.14)(r*2)
print("\nArea of Circle is:",a)
print("Enter Length: ")
l=float(input())
print("Enter Breadth: ")
b=float(input())
a=l*b
print("\nArea of Rectangle is:",a)
print("Enter Base: ")
b=float(input())
print("Enter  Height: ")
h=float(input())
a=((b*h)/2)
print("\nArea of Triangle is:",a)
print("Enter Length: ")
l=float(input())
a=(l**2)
print("\nArea of Square is:",a)